# name: ASimpleAuthKitDevProject

# packages:
#   ASimpleAuthKit: # You can name this after your package, or keep ASimpleAuthKitPackage.
#                   # This is just a label used by xcodegen.
#     path: .       # Points to the directory containing Package.swift

# # No need to define 'ASimpleAuthKit_XcodeprojLib' if your goal is just to work with the SPM package.
# # xcodegen will make the SPM library target/product available.

# targets:
#   # This section configures the "ASimpleAuthKitTests" target that comes from your Package.swift
#   ASimpleAuthKitTests:
#     type: bundle.unit-test
#     platform: iOS # MUST EXACTLY match the name of the .testTarget in Package.swift
#     # type, platform, sources, and primary dependencies are inherited from Package.swift
#     settings:
#       PRODUCT_BUNDLE_IDENTIFIER: oi.appsimple.ASimpleAuthKitTests
#       CODE_SIGN_ENTITLEMENTS: Tests/ASimpleAuthKitTests/ASimpleAuthKitTests.entitlements
#       GENERATE_INFOPLIST_FILE: YES # Usually not needed as SPM handles Info.plist for its targets
#                                    # but can be added if you have specific needs.
#     # If you had .xcodeproj-only dependencies for your tests, you'd add them here.
#     # The dependency on the "ASimpleAuthKit" library product is already defined
#     # in your Package.swift and will be respected.

# # schemes:
# #   ASimpleAuthKitDevScheme:
# #     build:
# #       targets:
# #         # ASimpleAuthKit: all       # Build the "ASimpleAuthKit" PRODUCT from Package.swift
# #         ASimpleAuthKitTests: test # Build the "ASimpleAuthKitTests" TARGET from Package.swift
# #     test:
# #       targets:
# #         - ASimpleAuthKitTests     # Run tests from the "ASimpleAuthKitTests" TARGET